# Generated by Django 5.0.2 on 2024-03-27 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='name',
            new_name='photo_name',
        ),
    ]
