# Generated by Django 5.0.2 on 2024-03-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0002_rename_name_gallery_photo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_HeadDes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_mes', models.CharField(max_length=600)),
                ('slider_mes', models.CharField(max_length=600)),
                ('service_mes', models.CharField(max_length=600)),
                ('blog_mes', models.CharField(max_length=600)),
                ('stuff_mes', models.CharField(max_length=600)),
            ],
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='message',
        ),
    ]
