# Generated by Django 5.0.2 on 2024-03-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_all_headdes_remove_gallery_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo_name',
            field=models.CharField(max_length=50),
        ),
    ]
