# Generated by Django 5.0.2 on 2024-03-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0007_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='logo',
            new_name='photo',
        ),
    ]
