# Generated by Django 5.0.2 on 2024-03-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0009_post_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(help_text='Image size should be width= 470x height=570', upload_to='media/post'),
        ),
    ]
