# Generated by Django 5.0.2 on 2024-03-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0010_alter_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_headdes',
            name='blog_mes',
            field=models.CharField(max_length=170),
        ),
        migrations.AlterField(
            model_name='all_headdes',
            name='gallery_mes',
            field=models.CharField(max_length=170),
        ),
        migrations.AlterField(
            model_name='all_headdes',
            name='service_mes',
            field=models.CharField(max_length=170),
        ),
        migrations.AlterField(
            model_name='all_headdes',
            name='slider_mes',
            field=models.CharField(max_length=170),
        ),
        migrations.AlterField(
            model_name='all_headdes',
            name='stuff_mes',
            field=models.CharField(max_length=170),
        ),
    ]
