# Generated by Django 5.0.2 on 2024-03-31 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0011_alter_all_headdes_blog_mes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desciption', models.TextField(max_length=280)),
                ('logo', models.ImageField(upload_to='media/logo')),
                ('pub_date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
