# Generated by Django 5.0.2 on 2024-03-31 06:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0013_alter_about_footer_desciption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='gallery',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
