# Generated by Django 5.0.2 on 2024-03-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0014_alter_gallery_options_gallery_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ozzy auto recycle', max_length=40)),
                ('aboutus', models.TextField(max_length=600)),
                ('photo', models.ImageField(help_text='Image size should be width= 800px height=650px', upload_to='media/about')),
                ('alt', models.CharField(max_length=20)),
                ('slogan', models.CharField(max_length=150)),
            ],
        ),
    ]
