# Generated by Django 5.0.2 on 2024-03-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0016_alter_about_aboutus_alter_about_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='slogan',
            field=models.TextField(help_text='max length is 150 character', max_length=150),
        ),
    ]
