# Generated by Django 5.0.2 on 2024-03-31 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0018_servicetype_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='tilte',
            new_name='title',
        ),
    ]
