# Generated by Django 5.0.2 on 2024-04-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0019_rename_tilte_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(help_text='photo width =1200px height = 800', upload_to='media/Gallery'),
        ),
    ]
