# Generated by Django 5.0.2 on 2024-04-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0020_alter_gallery_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=120),
        ),
    ]
