# Generated by Django 5.0.2 on 2024-04-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0021_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='alt',
            field=models.CharField(blank=True, help_text='please meaning full name for photo', max_length=40, null=True),
        ),
    ]
