# Generated by Django 5.0.2 on 2024-04-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0022_service_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=700),
        ),
    ]
