# Generated by Django 5.0.2 on 2024-05-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0023_alter_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_meta_title', models.CharField(blank=True, help_text='meta title should be 50-60 character', max_length=60, null=True)),
                ('about_meta_keyword', models.CharField(blank=True, help_text='meta keyword should be 10-20 meta keyword', max_length=220, null=True)),
                ('about_meta_desc', models.CharField(blank=True, help_text='meta description should be 155-160 character', max_length=160, null=True)),
                ('blog_meta_title', models.CharField(blank=True, help_text='meta title should be 50-60 character', max_length=60, null=True)),
                ('blog_meta_keyword', models.CharField(blank=True, help_text='meta keyword should be 10-20 meta keyword', max_length=220, null=True)),
                ('blog_meta_desc', models.CharField(blank=True, help_text='meta description should be 155-160 character', max_length=160, null=True)),
                ('contact_meta_title', models.CharField(blank=True, help_text='meta title should be 50-60 character', max_length=60, null=True)),
                ('contact_meta_keyword', models.CharField(blank=True, help_text='meta keyword should be 10-20 meta keyword', max_length=220, null=True)),
                ('contact_meta_desc', models.CharField(blank=True, help_text='meta description should be 155-160 character', max_length=160, null=True)),
                ('gallery_meta_title', models.CharField(blank=True, help_text='meta title should be 50-60 character', max_length=60, null=True)),
                ('gallery_meta_keyword', models.CharField(blank=True, help_text='meta keyword should be 10-20 meta keyword', max_length=220, null=True)),
                ('gallery_meta_desc', models.CharField(blank=True, help_text='meta description should be 155-160 character', max_length=160, null=True)),
                ('quote_meta_title', models.CharField(blank=True, help_text='meta title should be 50-60 character', max_length=60, null=True)),
                ('quote_meta_keyword', models.CharField(blank=True, help_text='meta keyword should be 10-20 meta keyword', max_length=220, null=True)),
                ('quote_meta_desc', models.CharField(blank=True, help_text='meta description should be 155-160 character', max_length=160, null=True)),
                ('index_meta_title', models.CharField(blank=True, help_text='meta title should be 50-60 character', max_length=60, null=True)),
                ('index_meta_keyword', models.CharField(blank=True, help_text='meta keyword should be 10-20 meta keyword', max_length=220, null=True)),
                ('index_meta_desc', models.CharField(blank=True, help_text='meta description should be 155-160 character', max_length=160, null=True)),
                ('service_meta_title', models.CharField(blank=True, help_text='meta title should be 50-60 character', max_length=60, null=True)),
                ('service_meta_keyword', models.CharField(blank=True, help_text='meta keyword should be 10-20 meta keyword', max_length=220, null=True)),
                ('service_meta_desc', models.CharField(blank=True, help_text='meta description should be 155-160 character', max_length=160, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='meta_desc',
            field=models.CharField(blank=True, help_text='meta description should be 155-160 character', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_keyword',
            field=models.CharField(blank=True, help_text='meta keyword should be 10-20 meta keyword', max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, help_text='meta title should be 50-60 character', max_length=60, null=True),
        ),
    ]
