# Generated by Django 5.0.2 on 2024-05-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0024_allmeta_post_meta_desc_post_meta_keyword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='meta_desc',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meta_keyword',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meta_title',
        ),
    ]
